[build]
  # اترك الـ base فارغاً أو "/" لأن package.json في الجذر
  base    = "" 
  
  # الأوامر تنفذ من الجذر، لكننا نوجه Next.js لمجلد renderer
  command = "npm install && next build renderer"
  
  # مكان المجلد الناتج عن البناء (غالباً يكون داخل renderer)
  publish = "renderer/out"

[build.environment]
  NODE_VERSION = "20"