[build]
  base    = "" 
  command = "npm install && npm run build"
  publish = "renderer/out"

[build.environment]
  NODE_VERSION = "20"
  # هذا السطر يمنع انهيار البناء بسبب التحذيرات التقنية في Node 20
  NODE_OPTIONS = "--no-deprecation"